app/models.py
from . import db

class Category(db.Model):
    __tablename__ = "category"
    id = db.Column(db.Integer,primary_key=True)
    cate_name = db.Column(db.String(50),nullable=False)
    superior = db.Column(db.String(50),nullable=False)
    #和Topic之间的关联关系和反向引用
    topics = db.relationship('Topic',backref='category',lazy='dynamic')

    def __repr__(self):
        return "<Category:%r>"%self.cate_name

class User(db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer,primary_key=True)
    loginname = db.Column(db.String(50),nullable=False)
    uname = db.Column(db.String(30),nullable=False)
    email = db.Column(db.String(200),nullable=False)
    url = db.Column(db.String(200))
    upwd = db.Column(db.String(30))
    is_author = db.Column(db.SmallInteger,default=0)
    #增加和topic之间的反向引用
    topics = db.relationship('Topic',backref='user',lazy='dynamic')
    #增加和reply之间的反向引用
    replies = db.relationship('Reply',backref='user',lazy='dynamic')
    #增加和message之间的反向引用
    messages = db.relationship('Message',backref='user',lazy='dynamic')
    #增加与topic之间的反向引用(多对多)
    third1_topics = db.relationship(
        'Topic',
        secondary='third1',
        lazy='dynamic',
        backref=db.backref('third1_user',lazy='dynamic')
    )

class Topic(db.Model):
    __tablename__ = 'topic'
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(200),nullable=False)
    pub_date = db.Column(db.DateTime,nullable=False)
    read_num = db.Column(db.Integer,default=0)
    content = db.Column(db.Text,nullable=False)
    images = db.Column(db.Text)
    # 一category对多topic
    category_id = db.Column(db.Integer,db.ForeignKey('category.id'))
    # 一user对多topic
    user_id = db.Column(db.Integer,db.ForeignKey('user.id'))

class Reply(db.Model):
    __tablename__='reply'
    id = db.Column(db.Integer,primary_key=True)
    content = db.Column(db.Text,nullable=False)
    reply_time = db.Column(db.DateTime)
    # 一topic对多reply
    topic_id = db.Column(db.Integer,db.ForeignKey('topic.id'))
    #一user对多reply
    user_id = db.Column(db.Integer,db.ForeignKey('user.id'))

class Message(db.Model):
    __tablename__='message'
    id = db.Column(db.Integer,primary_key=True)
    content = db.Column(db.Text, nullable=False)
    reply_time = db.Column(db.DateTime)
    user_id = db.Column(db.Integer,db.ForeignKey('user.id'))


#多对多，第三张表
Third1 = db.Table(
    'third1',
    db.Column('id',db.Integer,primary_key=True),
    db.Column('user_id',db.Integer,db.ForeignKey('user.id')),
    db.Column('topic_id',db.Integer,db.ForeignKey('topic.id'))
)

app/__init__.py
#工作
#1.创建Flask应用以及各种配置
#2.创建数据库实例
#3.通过蓝图关联其他的业务程序
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

import pymysql
pymysql.install_as_MySQLdb()

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)

    app.config['DEBUG']=True
    app.config['SQLALCHEMY_DATABASE_URI']='mysql://root:123456@localhost:3306/lgc_blog'
    app.config['SQLALCHEMY_COMMIT_ON_TEARDOWN']=True
    app.config['SECRET_KEY']='luoguichuan'

    db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .users import users as users_blueprint
    app.register_blueprint(users_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)

from . import views

app/main/views.py
import datetime
import os

from flask import render_template, session, request, redirect
#导入蓝图，用于构筑
from . import main
from ..models import *

@main.route('/')
def index_views():
    categories = Category.query.all()
    topics = Topic.query.all()
    if 'uid' in session and 'uname' in session:
        user = User.query.filter_by(id=session.get('uid')).first()
    return render_template('index.html',params=locals())


@main.route('/release',methods=['GET','POST'])
def release_views():
    #允许发表，实现作者的权限认证
    if request.method == 'GET':
        if 'uid' in session and 'uname' in session:
            user = User.query.filter_by(id=session.get('uid')).first()
            if user.is_author != 1:
                return redirect('/')
            else:
                categories = Category.query.all()
                return render_template('release.html',params=locals())
        else:
            return redirect('/login')
    #将发表的博客保存进数据库
    else:
        topic = Topic()
        topic.title = request.form.get('author')
        topic.category_id = request.form.get('category')
        topic.user_id = session.get('uid')
        topic.content = request.form.get('content')
        topic.pub_date = datetime.datetime.now().strftime("%Y-%m-%d")
        #如果有上传文件
        if request.files:
            f = request.files['picture']
            ftime = datetime.datetime.now().strftime("%Y%m%d%H%M%S%f")
            ext=f.filename.split('.')[1]
            filename=ftime+"."+ext
            topic.images = "upload/"+filename
            #将文件保存到服务器
            basedir = os.path.dirname(os.path.dirname(__file__))
            upload_path = os.path.join(basedir,'static/upload',filename)
            print(upload_path)
            f.save(upload_path)
        db.session.add(topic)
        return redirect('/')

@main.route('/list')
def list_views():
    categories = Category.query.all()
    topics = Topic.query.all()
    return render_template('list.html',params=locals())

@main.route('/info/<id>',methods=['GET'])
def info_views(id):
    topic = Topic.query.filter_by(id=id).first()
    user = User.query.filter_by(id=session.get('uid')).first()
    return render_template('info.html',params=locals())



@main.route('/about')
def about_views():
    topics = Topic.query.all()
    return render_template('about.html',params=locals())

@main.route('/time')
def time_views():
    topics = Topic.query.all()
    return render_template('time.html',params=locals())

@main.route('/photo')
def photo_views():
    topics= Topic.query.all()
    return render_template('photo.html',params=locals())

app/users/__init__.py
from flask import Blueprint
users = Blueprint('users',__name__)
from . import views

app/users/views.py
from . import users
from flask import render_template, session, request, redirect
from ..models import *
@users.route('/users')
def users_views():
    return "这是user访问路径"

@users.route('/login',methods=['GET','POST'])
def login_views():
    if request.method == 'GET':
        return render_template('login.html')
    else:
        #接收前端传递过来的数据
        loginname = request.form.get('username')
        upwd = request.form.get('password')
        #到数据库中去验证数据
        user = User.query.filter_by(loginname=loginname,upwd=upwd).first()
        if user:
            session['uid']=user.id
            session['uname']=user.uname
            return redirect('/')
        else:
            errMsg = "用户名或密码错误"
            return render_template('login.html',errMsg=errMsg)

@users.route('/logout')
def logout_views():
    #获取源地址,有源地址则返回,没有的话则跳转到首页
    url = request.headers.get('referer','/')
    print('源地址'+url)

    #判断登录信息是否在session中
    if 'uid' in session and 'uname' in session:
        del session['uid']
        del session['uname']
    return redirect(url)

@users.route('/register')
def register_views():
    return render_template('register.html')

app/templates/about.html
{% extends 'index.html' %}
{% block topfiles %}
<head>
  <meta charset="utf-8">
  <title>关于我－川哥博客</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="/static/images/bitbug_favicon.ico" type="image/x-icon" />
  <link href="/static/css/base.css" rel="stylesheet">
  <link href="/static/css/index.css" rel="stylesheet">
  <link href="/static/css/m.css" rel="stylesheet">
  <script src="/static/js/jquery.min.js" type="text/javascript"></script>
  <script src="/static/js/jquery.easyfader.min.js"></script>
  <script src="/static/js/scrollReveal.js"></script>
  <script src="/static/js/common.js"></script>
</head>
{% endblock %}
{% block blogsbox %}
  <div class="pagebg ab"> </div>
  <div class="container">
    <h1 class="t_nav"><span>人生苦短，我学python</span>
      <p class="n1">关于我</p>
    </h1>
    <div class="news_infos">
      <ul>
        <h2>About my blog</h2>
        <br />
        <p>
            希望能在程序员的路上越走越元
        </p>
        <br />
      </ul>
    </div>
    <div class="sidebar">
      <div class="about">
        <p class="avatar"> <img src="/static/images/avatar.jpg" alt=""> </p>
        <p class="abname">LGC</p>
        <p class="abposition">python开发工程师</p>
        <p class="abtext">一个技术宅男，很庆幸学习了python,进入了软件行列 </p>
      </div>
    </div>
  </div>
{% endblock %}
{% block sidebar %}
{% endblock %}

app/templates/footer.html
<p>Design by <a href=# target="_blank">皮爷の博客</a> <a href="#">蜀ICP备11002373号-1</a></p>

app/templates/header.html
<!--menu begin-->
<div class="menu">
    <nav class="nav" id="topnav">
        <h1 class="logo"><a href="index.html">皮爷の博客</a></h1>
        <li><a href="index.html">网站首页</a> </li>
        <li><a href="list.html">文章列表</a>
            <ul class="sub-nav">
                    <li><a href="list.html">Python</a></li>
                    <li><a href="list.html">python Web</a></li>
                    <li><a href="list.html">爬虫</a></li>
                    <li><a href="list.html">人工智能</a></li>
                    <li><a href="list.html">JS实例索引</a></li>
            </ul>
        </li>
        <li><a href="photo.html">我的相册</a>
        </li>
        <li><a href="time.html">时间轴</a> </li>
        <li><a href="gbook.html">留言</a> </li>
        <!-- <li><a href="info.html">内容页</a> </li> -->
        <li><a href="about.html">关于我</a> </li>
        <!--search begin-->
        <!-- <div id="search_bar" class="search_bar">
        <form  id="searchform" action="[!--news.url--]e/search/index.php" method="post" name="searchform">
          <input class="input" placeholder="想搜点什么呢..." type="text" name="keyboard" id="keyboard">
          <input type="hidden" name="show" value="title" />
          <input type="hidden" name="tempid" value="1" />
          <input type="hidden" name="tbname" value="news">
          <input type="hidden" name="Submit" value="搜索" />
          <span class="search_ico"></span>
        </form>
      </div> -->
        <!--search end-->
    </nav>
</div>
<!--menu end-->
<!--mnav begin-->
<div id="mnav">
    <h2><a href="index.html" class="mlogo">皮爷の博客</a><span class="navicon"></span></h2>
    <dl class="list_dl">
        <dt class="list_dt"> <a href="index.html">网站首页</a> </dt>
        <dt class="list_dt"> <a href="#">文章列表</a> </dt>
        <dd class="list_dd">
            <ul>
                    <li><a href="list.html">Python</a></li>
                    <li><a href="list.html">python Web</a></li>
                    <li><a href="list.html">爬虫</a></li>
                    <li><a href="list.html">人工智能</a></li>
                    <li><a href="list.html">JS实例索引</a></li>
            </ul>
        </dd>
        <dt class="list_dt"> <a href="photo.html">我的相册</a> </dt>
        <dt class="list_dt"> <a href="time.html">时间轴</a> </dt>
        <dt class="list_dt"> <a href="gbook.html">留言</a> </dt>
        <dt class="list_dt"> <a href="about.html">关于我</a> </dt>
    </dl>
</div>
<!--mnav end-->

app/templates/index.html
<!doctype html>
<html>

<head>
  {% block topfiles %}
  <meta charset="utf-8">
  <title>首页-川哥博客</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="/static/images/bitbug_favicon.ico" type="image/x-icon" />
  <link href="/static/css/base.css" rel="stylesheet">
  <link href="/static/css/index.css" rel="stylesheet">
  <link href="/static/css/m.css" rel="stylesheet">
  <script src="/static/js/jquery.min.js" type="text/javascript"></script>
  <script src="/static/js/jquery.easyfader.min.js"></script>
  <script src="/static/js/scrollReveal.js"></script>
  <script src="/static/js/common.js"></script>
  {% endblock topfiles %}
  {% block css %}
  {% endblock %}
</head>

<body>
{% block header %}
  <header id="header">
    <!--menu begin-->
    <div class="menu">
      <nav class="nav" id="topnav">
        <li><a href="/">首页</a> </li>
        <li><a href="/list">技术 · 工作</a>
          <ul class="sub-nav">
            {% for category in params.categories %}
                {% if category.superior == 'work' %}
                <li>
                  <a href="/list?cateid={{ category.id }}">{{ category.cate_name }}</a>
                </li>
                {% endif %}
            {% endfor %}
          </ul>
        </li>
        <li><a href="/photo">娱乐 · 生活</a>
          <ul class="sub-nav">
            {% for category in params.categories %}
                {% if category.superior == 'life' %}
                <li>
                  <a href="/photo?cateid={{ category.id }}">{{ category.cate_name }}</a>
                </li>
                {% endif %}
            {% endfor %}
          </ul>
        </li>
        <li><a href="/time">时间轴</a> </li>
        <li><a href="/release">发表</a> </li>
        <li><a href="/about">About Me</a></li>
      </nav>
    </div>
    {% if not params.user %}
    <h1 class="logo"><a href="/login" id="login" target="_blank">LGC</a></h1>
    {% else %}
    <a id="login" target="_blank">欢迎:{{ params.user.uname }}</a>
    <a href="/logout" id="register">退出</a>
    {% endif %}
    <!--menu end-->
  </header>
{% endblock header %}
{% block pagebg %}
{% endblock pagebg %}

  <article>
  {% block picsbox %}
  {% endblock %}
  {% block blogsbox %}
    <!--blogsbox begin-->
    <div class="blogsbox">
      <!-- 循环遍历服务器端读取出来的所有博客 -->
      {% for topic in params.topics %}
        {% if topic.category.superior == 'work' %}
        <div class="blogs" data-scroll-reveal="enter bottom over 1s">
          <h3 class="blogtitle"><a href="{{ url_for('main.info_views',id=topic.id) }}" target="_blank">{{topic.title}}</a></h3>
          {% if topic.images %}
          <span
            {% if loop.index % 2 == 0 %}
              class="blogpic"
            {% else %}
              class="bigpic"
            {% endif %}
          >
            <a href="{{ url_for('main.info_views',id=topic.id) }}" title="">
              <img src="/static/{{topic.images}}" alt="" topic_id="">
            </a>
          </span>
          {% endif %}
          <p class="blogtext">{{topic.content}}</p>
          <div class="bloginfo">
            <ul>
              <li class="lmname"><a href="info.html">{{topic.category.cate_name}}</a></li>
              <li class="timer">{{topic.pub_date.strftime("%Y-%m-%d")}}</li>
              <li class="view">{{topic.read_num}}已阅读</li>
            </ul>
          </div>
        </div>
        {% endif %}
      {% endfor %}
    </div>
  {% endblock %}
  {% block sidebar %}
    <!--sidebar begin-->
    <div class="sidebar">
      <div class="zhuanti">
        <h2 class="hometitle">My Life</h2>
        <ul>
        {% for topic in params.topics %}
          {% if topic.category.superior == 'life' %}
          <li><i><img src="/static/{{ topic.images }}"></i>
              <p>{{ topic.title }}<span><a href="#">阅读</a></span></p>
          </li>
          {% endif %}
        {% endfor %}
      </ul>
      </div>
      <div class="cloud">
        <h2 class="hometitle">实用链接</h2>
        <ul>
          <a href="#">社区：github.com</a>
          <a href="#">社区：stackoverflow.com</a>
          <a href="#">工具：djangoproject.com</a>
        </ul>
      </div>
      <div class="guanzhu" id="follow-us">
        <h2 class="hometitle">联系关注</h2>
        <ul>
          <li class="sina"><a href="#" target="_blank"><span>微博</span>P-o-R</a></li>
          <li class="qq"><a href="#" target="_blank"><span>QQ号</span>5731792240</a></li>
          <li class="email"><a href="#" target="_blank"><span>邮箱帐号</span>QQ邮箱</a></li>
        </ul>
      </div>
    </div>

{% endblock sidebar %}
  </article>
{% block footer %}
  <footer id="footer">
    <p>Design by LGC<a href=# target="_blank">个人博客</a> <a href="#">备XXXXXXXXX号-1</a></p>
  </footer>
{% endblock footer %}
{% block bottom %}
      <a href="#" class="cd-top">Top</a>
{% endblock bottom %}
</body>

</html>

app/templates/info.html
{% extends 'index.html' %}
{% block topfiles %}
	<meta charset="utf-8">
	<title>详情页－川哥博客</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="/static/images/bitbug_favicon.ico" type="image/x-icon" />
	<link rel="stylesheet" href="/static/css/comments.css">
	<link href="/static/css/base.css" rel="stylesheet">
	<link href="/static/css/index.css" rel="stylesheet">
	<link href="/static/css/m.css" rel="stylesheet">
	<script src="/static/js/jquery.min.js" type="text/javascript"></script>
	<script src="/static/js/jquery.easyfader.min.js"></script>
	<script src="/static/js/scrollReveal.js"></script>
	<script src="/static/js/wangEditor.js"></script>
	<script src="/static/js/common.js"></script>
	<script src="/static/js/xcConfirm.js"></script>
{% endblock topfiles %}

{% block css %}
	<script>
		var E = window.wangEditor
		var editor = new E('#editor')
		// 或者 var editor = new E( document.getElementById('editor') )
		editor.customConfig.menus = [
			'head', // 标题
			'bold', // 粗体
			'fontSize', // 字号
			'fontName', // 字体
			'italic', // 斜体
			'underline', // 下划线
			'strikeThrough', // 删除线
			'foreColor', // 文字颜色
			'backColor', // 背景颜色
			'link', // 插入链接
			'list', // 列表
			'justify', // 对齐方式
			'quote', // 引用
			'emoticon', // 表情
			'image', // 插入图片
			'table', // 表格
			'video', // 插入视频
			'undo', // 撤销
			'redo' // 重复
		]
		editor.create()
	</script>
{% endblock %}

{% block blogsbox %}
		<h1 class="t_nav">
			<p class="n1">文章</p>
		</h1>
		<div class="infosbox">
			<div class="newsview">
				<h3 class="news_title">{{ params.topic.title }}</h3>
				<div class="bloginfo">
					<ul>
						<li class="lmname"><a href="#">{{params.topic.category.cate_name}}</a></li>
						<li class="timer">{{params.topic.pub_date.strftime("%Y-%m-%d")}}</li>
						<li class="view">{{params.topic.read_num}}已阅读</li>
					</ul>
				</div>
				<div class="news_con">
	                {{ params.topic.content }}
				</div>
			</div>
		</div>
{% endblock %}
{% block sidebar %}
		<div class="sidebar">
			<div class="tuijian">
				<h2 class="hometitle">推荐文章</h2>
				<ul class="tjpic">
					<i><img src="/static/images/toppic01.jpg"></i>
					<p><a href="#">别让这些闹心的套路，毁了你的网页设计</a></p>
				</ul>
				<ul class="sidenews">
					<li> <i><img src="/static/images/toppic01.jpg"></i>
						<p><a href="#">别让这些闹心的套路，毁了你的网页设计</a></p>
						<span>2018-05-13</span>
					</li>
					<li> <i><img src="/static/images/toppic02.jpg"></i>
						<p><a href="#">给我模板PSD源文件，我给你设计HTML！</a></p>
						<span>2018-05-13</span>
					</li>
					<li> <i><img src="/static/images/v1.jpg"></i>
						<p><a href="#">别让这些闹心的套路，毁了你的网页设计</a></p>
						<span>2018-05-13</span>
					</li>
					<li> <i><img src="/static/images/v2.jpg"></i>
						<p><a href="#">给我模板PSD源文件，我给你设计HTML！</a></p>
						<span>2018-05-13</span>
					</li>
				</ul>
			</div>
		</div>
	</article>
{% endblock %}

app/templates/list.html
{% extends 'index.html' %}

{% block css%}
<style>
  @media screen and (min-width: 768px) and (max-width: 959px){
    article{
      width:90%;
      margin:15px auto 0;
    }
  }
</style>
{% endblock %}

{% block pagebg %}
  <div class="pagebg sh"></div>
{% endblock %}

{% block picsbox %}
<h1 class="t_nav">
  <span>人生苦短，我学python </span>
  <p class="n1">文章列表</p>
</h1>
{% endblock %}

{% block blogsbox %}
    <div class="blogsbox">
    {% for topic in params.topics %}
        {% if topic.category.superior == 'work' %}
        <div class="blogs" data-scroll-reveal="enter bottom over 1s">
            <h3 class="blogtitle"><a href="{{ url_for('main.info_views',id=topic.id) }}" target="_blank">{{topic.title}}</a></h3>
            <p class="blogtext"><a href="{{ url_for('main.info_views',id=topic.id) }}">{{topic.content}}</a></p>
            <div class="bloginfo">
                <ul>
                  <li class="lmname"><a href="info.html">{{topic.category.cate_name}}</a></li>
                  <li class="timer">{{topic.pub_date.strftime("%Y-%m-%d")}}</li>
                  <li class="view">{{topic.read_num}}已阅读</li>
                </ul>
             </div>
        </div>
        {% endif %}
    {% endfor %}
    </div>
{% endblock %}

{% block sidebar %}
	<div class="sidebar">
        <div class="tuijian">
            <h2 class="hometitle">推荐文章</h2>
            <ul class="tjpic">
                <i><img src="/static/images/python.jpg"></i>
                <p><a href="https://www.python.org/">python</a></p>
            </ul>
            <ul class="sidenews">
                <li> <i><img src="/static/images/django.jpg"></i>
                    <p><a href="https://www.djangoproject.com/">django</a></p>
                    <span>框架</span>
                </li>
                <li> <i><img src="/static/images/flask.jpg"></i>
                    <p><a href="http://flask.pocoo.org/">flask</a></p>
                    <span>框架</span>
                </li>
                <li> <i><img src="/static/images/mysql.jpg"></i>
                    <p><a href="https://www.mysql.com/">mysql</a></p>
                    <span>数据库</span>
                </li>
                <li> <i><img src="/static/images/mongodb.jpg"></i>
                    <p><a href="https://www.mongodb.com/">mongodb</a></p>
                    <span>数据库</span>
                </li>
            </ul>
        </div>
	</div>
{% endblock sidebar %}


app/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="/static/css/login_reglogin.css"/>
</head>
<body>
    {% if errMsg %}
    <script>
        alert('用户名不正确')
    </script>
    {% endif %}
	<div class="bg">
		<img src="/static/images/b.jpg" alt="">
	</div>
	<div class="main">
		<div class="header" >
			<h1>Login!</h1>
		</div>
		<p></p>
		<form action="/login" method="post">
			<ul class="right-form">
				<h2>Login:</h2>
				<li><input type="text" name="username" placeholder="Username" required/></li>
				<li><input type="password" name="password" placeholder="Password" required/></li>
				<input type="hidden" name="source_url" value="">
				<input type="submit" value="Login" >
				<div class="clear"> </div>
			</ul>
			<div class="clear"> </div>
		</form>
	</div>
	
</body>
</html>

app/templates/photo.html
{% extends 'index.html' %}
{% block topfiles %}
  <meta charset="utf-8">
  <title>首页-川哥博客</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="/static/images/bitbug_favicon.ico" type="image/x-icon" />
  <link href="/static/css/base.css" rel="stylesheet">
  <link href="/static/css/index.css" rel="stylesheet">
  <link href="/static/css/m.css" rel="stylesheet">
  <script src="/static/js/jquery.min.js" type="text/javascript"></script>
  <script src="/static/js/jquery.easyfader.min.js"></script>
  <script src="/static/js/scrollReveal.js"></script>
  <script src="/static/js/common.js"></script>
{% endblock %}


{% block blogsbox %}
  <div class="pagebg photo"></div>
  <div class="container">
    <h1 class="t_nav"><span>人生苦短，我学python</span>
      <p class="n1">文章列表</p>
    </h1>
    <div class="share">
      <ul>
        {% for topic in params.topics %}
            {% if topic.category.superior == 'life' %}
                <li>
                    <div class="shareli"><a href="{{ url_for('main.info_views',id=topic.id) }}" target="_blank">
                        <i><img src="/static/{{ topic.images }}"></i>
                        <h2><b>{{ topic.title }}</b></h2>
                        <span>{{ topic.category.cate_name }}</span>
                    </a>
                    </div>
                </li>
            {% endif %}
        {% endfor %}
      </ul>
    </div>
    <div class="pagelist">
        <a title="Total record">&nbsp;<b>上一页</b> </a>&nbsp;&nbsp;&nbsp;
        <b>1</b>&nbsp;&nbsp;
        <a href="#">下一页</a>&nbsp;
        <a href="/static/#">尾页</a></div>
  </div>
{% endblock %}
{% block sidebar %}
{% endblock %}


app/templates/register.html

<!DOCTYPE html>
<html>
<head>
		<meta charset="utf-8">
		<link href="css/login_reglogin.css" rel='stylesheet' type='text/css' />
		<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
		<div class="bg">
				<img src="images/c.jpg" alt="">
			</div>
	<div class="main">
		<div class="header" >
			<h1>创建一个新账户！</h1>
		</div>
		<p></p>
			<form action="#" method="post">
				<ul class="left-form">
					<h2>新账户:</h2>
					<li>
            <input type="text" name="username" placeholder="请输入用户名" required/>
						<div class="clear"> </div>
					</li> 
					<li>
            <input type="email" name="email" placeholder="请输入邮箱" required/>
						<div class="clear"> </div>
					</li> 
					<li>
            <input type="url" name="url" placeholder="请输入个人主站地址" required/>
						<div class="clear"> </div>
					</li> 
					<li>
            <input type="password" name="password" placeholder="请输入密码" required/>
						<div class="clear"> </div>
          </li>
          <li>
              <input type="password" name="password" placeholder="请再次确认密码" required/>
              <div class="clear"> </div>
            </li>
					<!--用于记录注册跳转来源，方便注册之后跳转之前的页面value="{ request.META.HTTP_REFERER }"-->
          <input type="hidden" name="source_url" >
					<input type="submit" value="创建并登录">
					<div class="clear"> </div>
				</ul>
				<div class="clear"> </div>
			</form>
	</div>
</body>
</html>